#ifndef CNC_TESTS_ALLOCATION_VERSION_H
#define CNC_TESTS_ALLOCATION_VERSION_H

#ifndef CNC_TESTS_EXPORT
#define CNC_TESTS_EXPORT
#endif
#ifdef CNC_TESTS_STATIC_LIBRARY_PREFIX
#define CNC_TESTS_ALLOC_NAME_MANGLE(a) ZTD_CONCAT_TOKENS_I_(CNC_TESTS_STATIC_LIBRARY_PREFIX, a)
#elif !defined(CNC_TESTS_ALLOC_NAME_MANGLE)
#define CNC_TESTS_ALLOC_NAME_MANGLE(a) a
#endif

#endif
