name: Ubuntu

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  LC_ALL: C.UTF-8

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: configure
      run: |
        cmake -B build -G Ninja -D ZTD_CUNEICODE_TESTS=ON -D ZTD_CUNEICODE_EXAMPLES=ON -D ZTD_CUNEICODE_GENERATE_SINGLE=ON

    - name: build
      run: |
        cmake --build build --config Debug
        cmake --build build --config Release

    - name: test
      run: |
        cd build
        ctest --build-config Debug
        ctest --build-config Release
